// Pawz Agent Engine — Native Rust AI agent runtime
// Direct AI API calls, in-process tool execution, and Tauri IPC
// for zero-network-hop communication.

pub mod agent_loop;
pub mod audit;
#[cfg(feature = "binary-ipc")]
pub mod binary_ipc;
pub mod http;
pub mod paths;
pub mod pricing;
pub mod providers;
pub mod sessions;
pub mod state;
pub mod tools;
pub mod types;
// commands module moved to crate::commands::channels — see src/commands/channels.rs
pub mod channels;
pub mod chat;
pub mod compaction;
pub mod constrained;
#[cfg(feature = "dex")]
pub mod dex;
#[cfg(feature = "channels")]
pub mod discord;
pub mod engram;
pub mod events;
pub mod forge;
pub mod injection;
#[cfg(feature = "channels")]
pub mod irc;
pub mod key_vault;
#[cfg(feature = "channels")]
pub mod matrix;
#[cfg(feature = "channels")]
pub mod mattermost;
pub mod mcp;
pub mod memory;
#[cfg(feature = "docker")]
pub mod n8n_engine;
#[cfg(feature = "channels")]
pub mod nextcloud;
#[cfg(feature = "channels")]
pub mod nostr;
pub mod oauth;
pub mod orchestrator;
#[cfg(feature = "plan-executor")]
pub mod plan;
pub mod provider_registry;
pub mod routing;
#[cfg(feature = "docker")]
pub mod sandbox;
pub mod skills;
#[cfg(feature = "channels")]
pub mod slack;
#[cfg(feature = "dex")]
pub mod sol_dex;
#[cfg(feature = "speculative")]
pub mod speculative;
#[cfg(feature = "swarm")]
pub mod swarm;
pub mod tasks;
#[cfg(feature = "channels")]
pub mod telegram;
pub mod telemetry;
pub mod tool_index;
pub mod tool_metadata;
pub mod tool_registry;
#[cfg(feature = "channels")]
pub mod twitch;
pub mod util;
#[cfg(feature = "browser")]
pub mod web;
#[cfg(feature = "channels")]
pub mod webchat;
#[cfg(feature = "channels")]
pub mod webhook;
#[cfg(feature = "channels")]
pub mod whatsapp;
